### ISSUE TITLE
按照Simple Usage的方式来使用提示如下 -T 也不行

### ISSUE THREAD

**Issue by Yer11214** [Plumbiu/twid#1]
![image](https://github.com/Plumbiu/twid/assets/39794167/4d5cfea0-1789-49e1-8ff8-372b2dd0e7e2)

**Comment by Plumbiu** [comment]
之前写的文件有问题，现在应该修好了

**Comment by Yer11214** [comment]
ok 测试了一下 提示
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: C:\Users\admin\.cache\puppeteer).
 
安装
`npx puppeteer browsers install chrome`

成功(*^▽^*)

感谢
